export const texts = {
  app: {
    name: 'Freelancer Manager',
  },
  nav: {
    jobs: 'Jobs',
    employees: 'Employees',
    report: 'Report',
    offDay: 'Off Day',
    me: 'Me',
  },
  fab: {
    new: 'New',
    newJob: 'New Job',
    newReport: 'New Report',
    newOffDay: 'New Off Day',
  },
  page: {
    jobs: {
      title: 'Jobs',
      empty: 'No jobs yet',
      emptyDesc: 'Create your first job to get started.',
      emptyAction: 'Add job',
      loading: 'Loading...',
      error: 'Failed to load jobs',
      noEmployee: 'No employee',
      tabWorking: 'Working',
      tabTransferring: 'Transfer',
      refresh: 'Refresh',
      openChat: 'Open chat',
      search: 'Search',
      searchPlaceholder: 'Search title, description…',
      filters: 'Filters',
      filterStatus: 'Status',
      filterRateType: 'Rate type',
      filterHirer: 'Hirer',
      filterTransferer: 'Transferer',
      filterAmount: 'Amount',
      filterAmountMin: 'Min',
      filterAmountMax: 'Max',
      filterClear: 'Clear all',
      filterApply: 'Apply',
      filterNoResults: 'No jobs match the current filters',
      emptyWorking: 'No active jobs',
      emptyTransferring: 'No transfers yet',
      jobTax: 'Job tax',
      personalTax: 'Personal tax',
      rate: 'Rate',
      detail: {
        title: 'Job Detail',
        back: 'Back',
        edit: 'Edit',
        cancel: 'Cancel',
        cancelReason: 'Cancel reason',
        cancelConfirmTitle: 'Cancel this job?',
        cancelConfirmDesc: 'Provide a reason — this is recorded on the job.',
        cancelReasonPlaceholder: 'Why is this job being cancelled?',
        cancelReasonRequired: 'Reason is required',
        cancelConfirmAction: 'Cancel job',
        cancelKeep: 'Keep job',
        cancelling: 'Cancelling...',
        cancelFailed: 'Failed to cancel job',
        cancelledToast: 'Job cancelled',
        startedToast: 'Job started',
        deletedToast: 'Job deleted',
        transferredToast: 'Transfer opened',
        delete: 'Delete',
        deleteConfirmTitle: 'Delete this job?',
        deleteConfirmDesc:
          'This permanently removes the job and its related records. This cannot be undone.',
        deleteConfirmAction: 'Delete job',
        deleteKeep: 'Keep',
        deleting: 'Deleting…',
        deleteFailed: 'Failed to delete job',
        hirer: 'Hirer',
        employee: 'Employee',
        you: 'You',
        amount: 'Amount',
        description: 'Description',
        notFound: 'Job not found',
        viewDetail: 'View detail',
        salaryMonth: 'This month salary',
        salaryUnits: 'work units',
        salaryReportDays: 'Reports',
        salaryPaidOff: 'Paid off',
        salaryUnpaidOff: 'Unpaid off',
        salaryHirerNet: 'Hirer net',
        salaryEmployeeNet: 'Employee net',
        calcPayment: 'Calculate payment',
        calcTitle: 'Payment calculation',
        integrate: 'Integrate data',
        integrateView: 'View integration',
        integrateTitle: 'Integrate historical data',
        integrateDesc:
          'One-time import of pre-existing reports + off days. Bypasses date and status checks.',
        integrateTabReports: 'Reports',
        integrateTabOffs: 'Off days',
        integrateEmpty: 'Add at least one report or one off day before integrating.',
        integrateConfirm: 'Integrate {reports} reports + {offs} off days',
        integrateRunning: 'Integrating\u2026',
        integrateDone: 'Integration complete',
        integrateFailed: 'Integration failed',
        integrateAlreadyDone: 'This job has already been integrated.',
        integrateResultTitle: 'Integration summary',
        integrateResultBy: 'Performed by',
        integrateResultAt: 'Performed at',
        integrateResultCounts:
          '{rOk} reports imported ({rFail} failed), {oOk} off days imported ({oFail} failed)',
        integrateResultNoEmployee:
          'Job has no employee — assign one before integrating.',
        calcBaseLabel: 'Base',
        calcTotalTax: 'Total tax',
        calcHirer: 'Hirer',
        calcEmployee: 'Employee',
        calcOT: 'Overtime',
        calcAssignOT: 'OT recipient',
        calcAssignOTHirer: 'Hirer',
        calcAssignOTEmployee: 'Employee',
        calcIncludeOtTax: 'Include tax on OT',
        calcStatsWorkingDays: 'Working days',
        calcStatsPaidOff: 'Paid off',
        calcStatsUnpaidOff: 'Unpaid off',
        calcStatsHoursLogged: 'Hours logged',
        calcStatsExpectedHours: 'Expected hours',
        calcStatsOtHours: 'OT hours',
        calcTableDate: 'Date',
        calcTableStatus: 'Status',
        calcTableHours: 'Hours',
        calcTableOt: 'OT',
        calcTableReportAt: 'Logged',
        status: 'Status',
        statusIdle: 'Idle',
        statusStarted: 'Started',
        statusCancelled: 'Cancelled',
        startedFrom: 'Started from',
        start: 'Start',
        transfer: 'Transfer',
        transferComingSoon: 'Transfer flow coming soon.',
        transferDialogTitle: 'Transfer this job',
        transferDialogDesc:
          'Pick a new employee or assign to yourself. Both parties (and the hirer) can chat on the transfer.',
        transferToMe: 'Assign to me',
        transferFieldEmployee: 'New employee',
        transferNote: 'Initial note (optional)',
        transferNotePlaceholder: 'Markdown supported — add handover context…',
        transferConfirm: 'Open transfer',
        transferCancel: 'Cancel',
        transferCreating: 'Opening…',
        transferFailed: 'Failed to open transfer',
        transferPickTargetError: 'Select a new employee or tick "Assign to me".',
        transferPendingBanner: 'Transfer in progress',
        transferFinish: 'Finish transfer',
        transferFinishConfirmTitle: 'Finish and hand over?',
        transferFinishConfirmDesc:
          'This clones the job for the new owner, links it back here, and marks this job as Transferred.',
        transferFinishing: 'Finishing…',
        transferFinished: 'Transferred',
        transferFromLabel: 'Transferred from',
        transferToLabel: 'Transferred to',
        transferredCallout: 'This job was handed off — work continues in the cloned job.',
        openChatWithTeam: 'Open chat with new team',
        openTeamChat: 'Transfer thead',
        chatPageTitle: 'Team chat',
        chatSourceLabel: 'Source',
        chatCloneLabel: 'Handover',
        chatTransferredAt: 'Transferred',
        chatNoAccess: 'You do not have access to this chat.',
        statusTransferred: 'Transferred',
        tabJob: 'Job',
        tabChat: 'Chat',
        chatEmpty: 'No messages yet. Start the handover thread below.',
        chatSend: 'Send',
        chatSending: 'Sending…',
        chatPlaceholder: 'Write a message (markdown supported)',
        chatSeen: 'Seen',
        chatSent: 'Sent',
        chatPin: 'Pin',
        chatUnpin: 'Unpin',
        chatPinned: 'Pinned',
        chatUnreadDivider: 'Unread messages',
        chatUnreadCount: 'unread',
        chatTabMessages: 'Messages',
        chatTabPinned: 'Pinned',
        chatEmptyPinned: 'No pinned messages yet.',
        transferToYou: 'Transfer to you',
        transferFromYou: 'Transfer pending',
        startConfirmTitle: 'Start this job?',
        startConfirmDesc:
          'Once started, the employee is locked. To change later you must transfer.',
        startNeedEmployeeTitle: 'Assign employee to start',
        startNeedEmployeeDesc: 'Select an employee before starting this job.',
        startConfirmAction: 'Start',
        startCancel: 'Cancel',
        starting: 'Starting...',
        startFailed: 'Failed to start job',
      },
      form: {
        newTitle: 'New Job',
        editTitle: 'Edit Job',
        save: 'Save',
        saving: 'Saving...',
        savedCreate: 'Job created',
        savedUpdate: 'Job updated',
        fieldTitle: 'Title',
        fieldDescription: 'Description',
        fieldDescriptionPlaceholder: 'Markdown supported',
        fieldEmployee: 'Employee',
        fieldEmployeePlaceholder: 'Search by name or email...',
        fieldEmployeeHint: 'Optional — leave blank for unassigned',
        fieldEmployeeEmpty: 'No employees found',
        fieldHirerRate: 'Hirer rate',
        fieldEmployeeRate: 'Employee rate',
        fieldEmployeeRateHint: 'Auto-computed as 100',
        rateSumError: 'Hirer rate + Employee rate must equal 100',
        fieldAmount: 'Amount',
        amountMinError: 'Amount must be at least 1,000 VND',
        fieldJobTaxRate: 'Job tax (%)',
        fieldPersonalTaxRate: 'Personal tax (%)',
        fieldRateType: 'Rate type',
        fieldRateTypePlaceholder: 'Select rate type',
        fieldPaymentDay: 'Pay day',
        fieldPaymentDayHint: 'Day of every month',
        workHoursSection: 'Working hours',
        fieldWorkStart: 'Work start',
        fieldWorkEnd: 'Work end',
        fieldLunchStart: 'Lunch start',
        fieldLunchEnd: 'Lunch end',
        fieldWorkingHours: 'Working hours',
        previewTitle: 'Estimated split',
        previewTaxSection: 'Tax',
        previewPaymentSection: 'Payment',
        previewHirerSection: 'Hirer',
        previewEmployeeSection: 'Employee',
        previewAmount: 'Amount',
        previewAmountJobTax: 'Job tax',
        previewAmountPersonalTax: 'Personal tax',
        previewAmountAfterTax: 'Amount after tax',
        previewGross: 'Gross',
        previewNet: 'Net',
        rateHourly: 'Hourly',
        rateDaily: 'Daily',
        rateMonthly: 'Monthly',
        titleRequired: 'Title is required',
        saveFailed: 'Failed to save job',
        confirmCancel: 'Cancel this job?',
        tabGeneral: 'General',
        tabPayment: 'Payment',
        confirmSaveTitle: 'Confirm job details',
        confirmSaveDesc: 'Review the salary breakdown before saving.',
        confirmSaveAction: 'Confirm & save',
        confirmSaveCancel: 'Back to edit',
        employeeLockedHint: 'Employee is locked after job is started — use Transfer to change.',
      },
    },
    reports: {
      title: 'Daily Reports',
      newTitle: 'New Report',
      editTitle: 'Edit Report',
      editLockedOtherDay: 'Only today\u2019s report can be edited.',
      save: 'Save',
      saving: 'Saving…',
      fieldJob: 'Job',
      fieldJobPlaceholder: 'Pick a job…',
      fieldDate: 'Date',
      fieldDescription: 'Description',
      fieldDescriptionPlaceholder: 'Markdown supported',
      jobRequired: 'Select a job',
      descriptionRequired: 'Description is required',
      fieldOtHours: 'OT hours',
      otHoursEditable: 'Enter overtime hours (past the work-day end).',
      otHoursLocked: 'OT opens for editing after the workday ends.',
      saveFailed: 'Failed to save report',
      saved: 'Report saved',
      empty: 'No reports yet',
      emptyDesc: 'Log your first daily report to track work.',
      emptyAction: 'Add report',
      statusOff: 'Off',
      statusWorking: 'Working',
      statusEmpty: 'Nothing logged',
      dayDetailTitle: 'Day detail',
      reportsSection: 'Reports',
      offSection: 'Off days',
      otHours: 'OT',
      noReports: 'No reports for this day.',
      noOff: 'Not marked as off.',
      editedTimes: 'Edited {n} time(s)',
      historyTitle: 'Edit history',
      edit: 'Edit',
      copy: 'Copy content',
      noJobs: 'No jobs to log against.',
      noReportForJob: 'No report for this job today.',
    },
    offDays: {
      title: 'Off Days',
      newTitle: 'New Off Day',
      editTitle: 'Edit Off Day',
      editLockedOtherDay: 'Only today\u2019s off day can be edited.',
      save: 'Save',
      saving: 'Saving…',
      fieldJob: 'Job',
      fieldJobPlaceholder: 'Pick a job…',
      fieldType: 'Type',
      fieldTitle: 'Title',
      fieldTitlePlaceholder: 'e.g. Sick leave',
      fieldDescription: 'Note',
      fieldDescriptionPlaceholder: 'Optional — context for the hirer',
      typeSAL: 'Paid',
      typeNOT_SAL: 'Unpaid',
      fieldPartialOff: 'Partial hours off',
      fieldPartialOffPlaceholder: 'Leave blank for full day',
      fieldPartialOffHint: 'Hours left early — must be less than the job\'s working hours.',
      jobRequired: 'Select a job',
      titleRequired: 'Title is required',
      saveFailed: 'Failed to save off day',
      saved: 'Off day saved',
      dayDetailTitle: 'Off days',
      noOffForJob: 'No off day on this job today.',
      noOffs: 'No off days for this day.',
      noJobs: 'No jobs to log against.',
      edit: 'Edit',
      delete: 'Delete',
      deleteConfirmTitle: 'Remove this off day?',
      deleteConfirmAction: 'Delete',
      deleteKeep: 'Keep',
    },
    profile: {
      title: 'Profile',
      signOut: 'Sign out',
      signingOut: 'Signing out...',
      signOutConfirmTitle: 'Sign out',
      signOutConfirmDesc: 'You will be returned to the login screen.',
      signOutFailed: 'Failed to sign out',
      cancel: 'Cancel',
      changePassword: 'Change password',
      changePasswordDesc: 'Update the password you use to sign in.',
      fieldNewPassword: 'New password',
      fieldConfirmPassword: 'Confirm password',
      passwordTooShort: 'Password must be at least 6 characters.',
      passwordMismatch: 'Passwords do not match.',
      changePasswordSave: 'Update password',
      changePasswordSaving: 'Updating…',
      changePasswordSuccess: 'Password updated.',
      changePasswordFailed: 'Failed to update password',
    },
    employees: {
      title: 'Employees',
      empty: 'No employees yet',
      emptyDesc: 'Create accounts for your employees to get started.',
      newEmployee: 'New employee',
      newEmployeeTitle: 'Create employee account',
      newEmployeeDesc:
        'A random password is generated. Email and password are copied to your clipboard.',
      fieldEmail: 'Email',
      fieldEmailPlaceholder: 'employee@example.com',
      emailRequired: 'Email is required',
      emailInvalid: 'Enter a valid email',
      emailTaken: 'An account with this email already exists',
      create: 'Create',
      creating: 'Creating…',
      cancel: 'Cancel',
      createdToast: 'Account created — credentials copied to clipboard.',
      createFailed: 'Failed to create account',
      clipboardFailed: 'Account created but clipboard copy failed.',
    },
  },
} as const

export type Texts = typeof texts

type Prev = [never, 0, 1, 2, 3, 4, 5, 6, 7]

type ComputeTextPath<T, D extends number = 5> = [D] extends [0]
  ? never
  : T extends object
    ? {
        [K in keyof T & string]: T[K] extends string
          ? K
          : `${K}.${ComputeTextPath<T[K], Prev[D]> & string}`
      }[keyof T & string]
    : never

export type TextPath = ComputeTextPath<Texts>
