// Auto-generated by npm run sp:gen-types — do not edit manually

export type JobStatus = 'idle' | 'started' | 'cancelled' | 'transferred'

export type OffDateType = 'SAL' | 'NOT_SAL'

export type RateType = 'hourly' | 'daily' | 'monthly'

export type TransferStatus = 'pending' | 'finished'

export type UserRole = 'hirer' | 'employee'

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: '12'
  }
  public: {
    Tables: {
      copy_templates: {
        Row: {
          id: string
          user_id: string
          name: string
          format: Record<string, unknown>
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          format?: Record<string, unknown>
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          format?: Record<string, unknown>
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      daily_report_edit: {
        Row: {
          id: string
          report_id: string
          description_before: string | null
          description_after: string | null
          edited_by: string
          edited_at: string
        }
        Insert: {
          id?: string
          report_id: string
          description_before?: string | null
          description_after?: string | null
          edited_by: string
          edited_at?: string
        }
        Update: {
          id?: string
          report_id?: string
          description_before?: string | null
          description_after?: string | null
          edited_by?: string
          edited_at?: string
        }
        Relationships: []
      }
      daily_reports: {
        Row: {
          id: string
          job_id: string
          user_id: string
          description: string | null
          estimate: string | null
          notes: string | null
          report_date: string
          created_at: string
          updated_at: string
          ot_hours: number | null
        }
        Insert: {
          id?: string
          job_id: string
          user_id: string
          description?: string | null
          estimate?: string | null
          notes?: string | null
          report_date: string
          created_at?: string
          updated_at?: string
          ot_hours?: number | null
        }
        Update: {
          id?: string
          job_id?: string
          user_id?: string
          description?: string | null
          estimate?: string | null
          notes?: string | null
          report_date?: string
          created_at?: string
          updated_at?: string
          ot_hours?: number | null
        }
        Relationships: []
      }
      export_templates: {
        Row: {
          id: string
          user_id: string
          name: string
          columns: Record<string, unknown>
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          columns?: Record<string, unknown>
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          columns?: Record<string, unknown>
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      job_integrations: {
        Row: {
          id: string
          job_id: string
          performed_by: string
          performed_at: string
          reports_imported: number
          reports_failed: number
          off_dates_imported: number
          off_dates_failed: number
          summary: Record<string, unknown>
        }
        Insert: {
          id?: string
          job_id: string
          performed_by: string
          performed_at?: string
          reports_imported?: number
          reports_failed?: number
          off_dates_imported?: number
          off_dates_failed?: number
          summary?: Record<string, unknown>
        }
        Update: {
          id?: string
          job_id?: string
          performed_by?: string
          performed_at?: string
          reports_imported?: number
          reports_failed?: number
          off_dates_imported?: number
          off_dates_failed?: number
          summary?: Record<string, unknown>
        }
        Relationships: []
      }
      job_schedules: {
        Row: {
          id: string
          job_id: string
          title: string
          description: string | null
          day_of_week: number | null
          day_of_month: number | null
          time_of_day: string | null
          schedule_type: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_id: string
          title: string
          description?: string | null
          day_of_week?: number | null
          day_of_month?: number | null
          time_of_day?: string | null
          schedule_type: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          title?: string
          description?: string | null
          day_of_week?: number | null
          day_of_month?: number | null
          time_of_day?: string | null
          schedule_type?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      job_transfer: {
        Row: {
          id: string
          job_id: string
          from_user_id: string
          to_user_id: string
          transferred_by: string
          reason: string | null
          created_at: string
          status: TransferStatus
          new_job_id: string | null
          finished_at: string | null
        }
        Insert: {
          id?: string
          job_id: string
          from_user_id: string
          to_user_id: string
          transferred_by: string
          reason?: string | null
          created_at?: string
          status?: TransferStatus
          new_job_id?: string | null
          finished_at?: string | null
        }
        Update: {
          id?: string
          job_id?: string
          from_user_id?: string
          to_user_id?: string
          transferred_by?: string
          reason?: string | null
          created_at?: string
          status?: TransferStatus
          new_job_id?: string | null
          finished_at?: string | null
        }
        Relationships: []
      }
      jobs: {
        Row: {
          id: string
          hirer_id: string
          employee_id: string | null
          hirer_rate: number
          employee_rate: number
          amount: number
          job_tax_rate: number
          description: string | null
          created_at: string
          updated_at: string
          metadata: Record<string, unknown>
          status: JobStatus
          cancel_reason: string | null
          rate_type: RateType
          title: string
          personal_tax_rate: number
          started_at: string | null
          transferred_from_job_id: string | null
          payment_day: number | null
          work_start: string
          work_end: string
          lunch_start: string | null
          lunch_end: string | null
          working_hours: number
        }
        Insert: {
          id?: string
          hirer_id: string
          employee_id?: string | null
          hirer_rate: number
          employee_rate: number
          amount: number
          job_tax_rate?: number
          description?: string | null
          created_at?: string
          updated_at?: string
          metadata?: Record<string, unknown>
          status?: JobStatus
          cancel_reason?: string | null
          rate_type?: RateType
          title?: string
          personal_tax_rate?: number
          started_at?: string | null
          transferred_from_job_id?: string | null
          payment_day?: number | null
          work_start?: string
          work_end?: string
          lunch_start?: string | null
          lunch_end?: string | null
          working_hours?: number
        }
        Update: {
          id?: string
          hirer_id?: string
          employee_id?: string | null
          hirer_rate?: number
          employee_rate?: number
          amount?: number
          job_tax_rate?: number
          description?: string | null
          created_at?: string
          updated_at?: string
          metadata?: Record<string, unknown>
          status?: JobStatus
          cancel_reason?: string | null
          rate_type?: RateType
          title?: string
          personal_tax_rate?: number
          started_at?: string | null
          transferred_from_job_id?: string | null
          payment_day?: number | null
          work_start?: string
          work_end?: string
          lunch_start?: string | null
          lunch_end?: string | null
          working_hours?: number
        }
        Relationships: []
      }
      jobs_log: {
        Row: {
          id: string
          job_id: string
          user_id: string
          action: string
          detail: Record<string, unknown>
          created_at: string
        }
        Insert: {
          id?: string
          job_id: string
          user_id: string
          action: string
          detail?: Record<string, unknown>
          created_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          user_id?: string
          action?: string
          detail?: Record<string, unknown>
          created_at?: string
        }
        Relationships: []
      }
      off_dates: {
        Row: {
          id: string
          job_id: string
          user_id: string
          title: string
          description: string | null
          type: OffDateType
          date: string
          created_at: string
          partial_off_hours: number | null
        }
        Insert: {
          id?: string
          job_id: string
          user_id: string
          title: string
          description?: string | null
          type: OffDateType
          date: string
          created_at?: string
          partial_off_hours?: number | null
        }
        Update: {
          id?: string
          job_id?: string
          user_id?: string
          title?: string
          description?: string | null
          type?: OffDateType
          date?: string
          created_at?: string
          partial_off_hours?: number | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          role: UserRole
          created_at: string
          updated_at: string
          settings: Record<string, unknown>
        }
        Insert: {
          id: string
          email: string
          full_name: string
          role: UserRole
          created_at?: string
          updated_at?: string
          settings?: Record<string, unknown>
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          role?: UserRole
          created_at?: string
          updated_at?: string
          settings?: Record<string, unknown>
        }
        Relationships: []
      }
      salary_snapshots: {
        Row: {
          id: string
          job_id: string
          employee_id: string
          hirer_rate: number
          employee_rate: number
          amount: number
          job_tax_rate: number
          period_month: number
          period_year: number
          off_days_sal: number
          off_days_not_sal: number
          final_amount: number
          created_at: string
          personal_tax_rate: number
        }
        Insert: {
          id?: string
          job_id: string
          employee_id: string
          hirer_rate: number
          employee_rate: number
          amount: number
          job_tax_rate: number
          period_month: number
          period_year: number
          off_days_sal?: number
          off_days_not_sal?: number
          final_amount: number
          created_at?: string
          personal_tax_rate?: number
        }
        Update: {
          id?: string
          job_id?: string
          employee_id?: string
          hirer_rate?: number
          employee_rate?: number
          amount?: number
          job_tax_rate?: number
          period_month?: number
          period_year?: number
          off_days_sal?: number
          off_days_not_sal?: number
          final_amount?: number
          created_at?: string
          personal_tax_rate?: number
        }
        Relationships: []
      }
      transfer_message: {
        Row: {
          id: string
          transfer_id: string
          author_id: string
          content: string
          pinned: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          transfer_id: string
          author_id: string
          content: string
          pinned?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          transfer_id?: string
          author_id?: string
          content?: string
          pinned?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      transfer_message_read: {
        Row: {
          message_id: string
          user_id: string
          read_at: string
        }
        Insert: {
          message_id: string
          user_id: string
          read_at?: string
        }
        Update: {
          message_id?: string
          user_id?: string
          read_at?: string
        }
        Relationships: []
      }
      variable_mappings: {
        Row: {
          id: string
          user_id: string
          name: string
          table_name: string
          field: string
          fallback: Record<string, unknown> | null
          transformer: Record<string, unknown> | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          table_name: string
          field: string
          fallback?: Record<string, unknown> | null
          transformer?: Record<string, unknown> | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          table_name?: string
          field?: string
          fallback?: Record<string, unknown> | null
          transformer?: Record<string, unknown> | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      job_status: JobStatus
      off_date_type: OffDateType
      rate_type: RateType
      transfer_status: TransferStatus
      user_role: UserRole
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
