import fs from 'fs'
import path from 'path'
import { getConfig, runSQL } from './env.mjs'

const { url, key } = getConfig()
const OUTPUT = path.resolve('src/types/database.ts')

// Map Postgres types to TypeScript types
function pgToTs(dataType, udtName, isNullable) {
  let ts
  switch (udtName) {
    case 'uuid':
    case 'text':
    case 'varchar':
    case 'char':
    case 'citext':
    case 'bpchar':
    case 'name':
    case 'date':
    case 'time':
    case 'timetz':
    case 'timestamp':
    case 'timestamptz':
      ts = 'string'
      break
    case 'int2':
    case 'int4':
    case 'int8':
    case 'float4':
    case 'float8':
    case 'numeric':
    case 'money':
      ts = 'number'
      break
    case 'bool':
      ts = 'boolean'
      break
    case 'json':
    case 'jsonb':
      ts = 'Record<string, unknown>'
      break
    case '_text':
      ts = 'string[]'
      break
    case '_int4':
    case '_int8':
      ts = 'number[]'
      break
    case '_uuid':
      ts = 'string[]'
      break
    default:
      // Could be a user-defined enum
      if (dataType === 'USER-DEFINED') {
        ts = udtName // will be resolved to enum type name
      } else if (dataType === 'ARRAY') {
        ts = 'unknown[]'
      } else {
        ts = 'unknown'
      }
  }
  return ts
}

// Fetch enums
const enums = await runSQL(url, key, `
  SELECT t.typname AS enum_name, e.enumlabel AS enum_value
  FROM pg_type t
  JOIN pg_enum e ON t.oid = e.enumtypid
  JOIN pg_namespace n ON t.typnamespace = n.oid
  WHERE n.nspname = 'public'
  ORDER BY t.typname, e.enumsortorder
`)

const enumMap = {}
if (Array.isArray(enums)) {
  for (const { enum_name, enum_value } of enums) {
    if (!enumMap[enum_name]) enumMap[enum_name] = []
    enumMap[enum_name].push(enum_value)
  }
}

// Fetch tables via DISTINCT on information_schema.columns
const tables = await runSQL(url, key, `
  SELECT DISTINCT table_name
  FROM information_schema.columns
  WHERE table_schema = 'public' AND LEFT(table_name, 1) != '_'
  ORDER BY table_name
`)

// Fetch columns for all tables
const columns = await runSQL(url, key, `
  SELECT
    c.table_name,
    c.column_name,
    c.data_type,
    c.udt_name,
    c.is_nullable,
    c.column_default,
    c.is_identity,
    CASE WHEN pk.column_name IS NOT NULL THEN 'YES' ELSE 'NO' END AS is_primary
  FROM information_schema.columns c
  LEFT JOIN (
    SELECT ku.table_name, ku.column_name
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage ku
      ON tc.constraint_name = ku.constraint_name
    WHERE tc.constraint_type = 'PRIMARY KEY'
      AND tc.table_schema = 'public'
  ) pk ON c.table_name = pk.table_name AND c.column_name = pk.column_name
  WHERE c.table_schema = 'public'
    AND c.table_name NOT LIKE '\\_%' ESCAPE '\\'
  ORDER BY c.table_name, c.ordinal_position
`)

// Group columns by table
const tableColumns = {}
if (Array.isArray(columns)) {
  for (const col of columns) {
    if (!tableColumns[col.table_name]) tableColumns[col.table_name] = []
    tableColumns[col.table_name].push(col)
  }
}

// Convert enum name to PascalCase type name
function toPascalCase(str) {
  return str.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase())
}

// Generate output
let out = '// Auto-generated by npm run sp:gen-types — do not edit manually\n\n'

// Enum types
for (const [name, values] of Object.entries(enumMap)) {
  const typeName = toPascalCase(name)
  out += `export type ${typeName} = ${values.map((v) => `'${v}'`).join(' | ')}\n\n`
}

// Resolve type — check if it's an enum
function resolveType(dataType, udtName, isNullable) {
  let ts = pgToTs(dataType, udtName, isNullable)
  // If it matches an enum name, use the PascalCase type
  if (enumMap[ts]) {
    ts = toPascalCase(ts)
  }
  if (isNullable === 'YES') {
    ts = `${ts} | null`
  }
  return ts
}

// Database interface
out += 'export interface Database {\n'
out += '  __InternalSupabase: {\n'
out += "    PostgrestVersion: '12'\n"
out += '  }\n'
out += '  public: {\n'
out += '    Tables: {\n'

for (const { table_name } of tables) {
  const cols = tableColumns[table_name] || []
  out += `      ${table_name}: {\n`

  // Row type
  out += '        Row: {\n'
  for (const col of cols) {
    const ts = resolveType(col.data_type, col.udt_name, col.is_nullable)
    out += `          ${col.column_name}: ${ts}\n`
  }
  out += '        }\n'

  // Insert type (defaults and generated columns are optional)
  out += '        Insert: {\n'
  for (const col of cols) {
    const ts = resolveType(col.data_type, col.udt_name, col.is_nullable)
    const hasDefault = col.column_default !== null && col.column_default !== ''
    const isGenerated = col.is_identity === 'YES'
    const isPrimary = col.is_primary === 'YES'
    const optional = hasDefault || isGenerated || (isPrimary && hasDefault) || col.is_nullable === 'YES'
    out += `          ${col.column_name}${optional ? '?' : ''}: ${ts}\n`
  }
  out += '        }\n'

  // Update type (all optional)
  out += '        Update: {\n'
  for (const col of cols) {
    const ts = resolveType(col.data_type, col.udt_name, col.is_nullable)
    out += `          ${col.column_name}?: ${ts}\n`
  }
  out += '        }\n'

  out += '        Relationships: []\n'
  out += '      }\n'
}

out += '    }\n'
out += '    Views: Record<string, never>\n'
out += '    Functions: Record<string, never>\n'
out += '    Enums: {\n'
for (const [name] of Object.entries(enumMap)) {
  out += `      ${name}: ${toPascalCase(name)}\n`
}
out += '    }\n'
out += '  }\n'
out += '}\n'

// Helper types
out += `
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
`

fs.writeFileSync(OUTPUT, out)
console.log(`✓ Generated ${OUTPUT}`)
console.log(`  ${tables.length} tables, ${Object.keys(enumMap).length} enums`)
